os: linux
dist: noble
language: generic
addons:
  apt:
    packages:
      - libxml-xpath-perl
services:
  - docker

git:
  depth: false

env:
  global:
    - DOCKER_ORG=zencash
    - IMAGE_NAME=sc-ci-base
    - NEED_CARGO_README=false
    - NEED_NPM=false
    - NEED_WASMPACK=false

script:
  - ci/travis_keep_alive.sh
  - ci/tests.sh

jobs:
  include:
    - name: stable
      env: IMAGE_TAG='focal_rust-stable_latest' TESTS='010,015,020,030,040'
    - name: nightly
      env: IMAGE_TAG='focal_rust-nightly_latest' TESTS='010,015,020,030,040'
