[package]
name = "fflonk_verifier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
digest = "0.10.7"
sha3 = "0.10.8"
substrate-bn = "0.6.0"
thiserror = "1.0.50"

[dev-dependencies]
pretty_assertions = "1.4.0"
rstest = { version = "0.18.2", default-features = false }
hex-literal = "0.4.1"
rand = "0.8.5"
